apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-and-mongodb
  template:
    metadata:
      labels:
        app: app-and-mongodb
    spec:
      containers:
      - name: nodejs-app
        image: harika5141/jenkins_capsuleproject-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://localhost:27017/restaurant"
        - name: PORT
          value: "3000"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        