apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 80          # Exposes the service on port 80 externally
    targetPort: 3000   # The port your Node.js application listens on inside the container
  type: NodePort   # LoadBalancer to expose the service to external traffic

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017       # Exposes MongoDB service on port 27017 internally
    targetPort: 27017  # The port MongoDB listens on inside the container
  type: ClusterIP      # Internal communication for MongoDB, no external exposure
